{
  "language": "java",
  "sudo": false,
  "jdk": [
    "openjdk11"
  ],
  "script": [
    "cd ./CPIT252-Lab5/lab-5-main/",
    "mvn clean package",
    "mvn test package",
    "cd ..",
    “cd ..”,
    "cd ./lab-03-main",
    "mvn clean package",
    "mvn test package"
  ],
  "after_success": [
    "bash <(curl -s https://codecov.io/bash)"
  ]
}
